export const Movielist=[
   {imgsrc:"https://images4.alphacoders.com/653/thumb-1920-653613.jpg",
    movie:"The Force Awakens",
    konc:"hollywood",
   link:"./Videos/vid-force.mp4"},
   {imgsrc: "https://images2.alphacoders.com/551/thumb-1920-551538.jpg",
    movie:" Iron Man",
    konc:"hollywood",
    link:"./Videos/vid-iron.mp4"},
   {imgsrc :"https://images7.alphacoders.com/653/thumb-1920-653797.jpg",
   movie:" The Force Awakens",
   konc:"hollywood",
   link:""},
   {imgsrc:"https://images7.alphacoders.com/671/thumb-1920-671281.jpg",
   movie:"Fight ",
   konc:"hollywood",
   link:""},
   {imgsrc: "https://images5.alphacoders.com/677/thumb-1920-677723.jpg",
   movie:"Suicide Squad",
   konc:"hollywood",
   link:""},
   {imgsrc:  "https://images8.alphacoders.com/463/thumb-1920-463476.jpg",
   movie:"Joker",
   konc:"hollywood",
   link:""},
   {imgsrc: "https://images5.alphacoders.com/721/thumb-1920-721135.jpg",
   movie:"Justice League",
   konc:"hollywood",
   link:""},
   {imgsrc: "https://images5.alphacoders.com/114/thumb-1920-1142280.jpg",
   movie:"SpiderMan",
   konc:"hollywood",
   link:""},
   {imgsrc:"https://images2.alphacoders.com/721/thumb-1920-721152.jpg",
   movie:"Wonder Women",
   konc:"hollywood",
   link:""},
   {imgsrc: "https://images4.alphacoders.com/559/thumb-1920-559552.jpg",
   movie:"Transformation age of extinction",
   konc:"hollywood",
   link:""},
   {imgsrc:"https://images3.alphacoders.com/606/thumb-1920-606650.jpg",
   movie:"Batman vs Spiderman",
   konc:"hollywood",
   link:""},
   {imgsrc: "https://images2.alphacoders.com/236/thumb-1920-236612.jpg",
   movie:"Ghost rider",
   konc:"hollywood",
   link:""},
   {imgsrc: "https://images8.alphacoders.com/677/thumb-1920-677720.jpg",
   movie:"Suicide Squad",
   konc:"hollywood",
   link:""},
   {imgsrc: "https://images2.alphacoders.com/671/thumb-1920-671277.jpg",
   movie:"The Force Awakens",
   konc:"hollywood",
   link:""},
   {imgsrc: "https://images4.alphacoders.com/900/thumb-1920-900361.jpg",
   movie:"Black Panther",
   konc:"hollywood",
   link:""},
   {imgsrc:"https://images2.alphacoders.com/608/thumb-1920-60852.jpg",
   movie:"Wall E",
   konc:"hollywood",
   link:""},
   {imgsrc: "https://images2.alphacoders.com/210/thumb-1920-210150.jpg",
   movie:"Spiderman 2",
   konc:"hollywood",
   link:""},
   {imgsrc: "https://images7.alphacoders.com/402/thumb-1920-402190.jpg",
   movie:"Black Widow",
   konc:"hollywood",
   link:""},
   {imgsrc: "https://images2.alphacoders.com/589/thumb-1920-589251.jpg",
   movie:" Fast and Furios",
   konc:"hollywood",
   link:""},
   {imgsrc: "https://images4.alphacoders.com/759/thumb-1920-759351.jpg",
   movie:"Docter Strange",
   konc:"hollywood",
   link:""},
   {imgsrc: "https://images3.alphacoders.com/948/thumb-1920-948864.jpg",
   movie:"Venom",
   konc:"hollywood",
   link:""},
   {imgsrc: "https://images6.alphacoders.com/712/thumb-1920-712995.jpg",
   movie:"Jungle Book",
   konc:"hollywood",
   link:""},
   {imgsrc: "https://images6.alphacoders.com/898/thumb-1920-898734.jpg",
   movie:"Black Panther",
   konc:"hollywood",
   link:""},
   {imgsrc:"https://images3.alphacoders.com/819/thumb-1920-819478.jpg",
   movie:"Root",
   konc:"hollywood",
   link:""},
   {imgsrc: "https://images7.alphacoders.com/915/thumb-1920-915141.jpg",
   movie:"Thor",
   konc:"hollywood",
   link:""},
   {imgsrc: "https://images3.alphacoders.com/738/thumb-1920-738660.jpg",
   movie:"Thor:Ragnarok ",
   konc:"hollywood",
   link:""},
   {imgsrc:"https://images6.alphacoders.com/714/thumbbig-714381.webp",
   movie:"Suicide Squad",
   konc:"hollywood",
   link:""},
   {imgsrc:"https://images5.alphacoders.com/757/thumbbig-757038.webp",
   movie:"Moana",
   konc:"hollywood",
   link:""},
   {imgsrc:"https://images2.alphacoders.com/869/thumbbig-869847.webp",
   movie:"Titanic",
   konc:"hollywood",
   link:""},
   {imgsrc:"https://images5.alphacoders.com/744/thumbbig-744742.webp",
   movie:"Logan",
   konc:"hollywood",
   link:""},
   {imgsrc:"https://images4.alphacoders.com/960/thumbbig-960281.webp",
   movie:"The Spider-Verse",
   konc:"hollywood",
   link:""},
   {imgsrc:"https://images6.alphacoders.com/614/thumbbig-614315.webp",
   movie:"Pirates of Carribean",
   konc:"hollywood",
   link:""},
   {imgsrc:"https://images4.alphacoders.com/100/thumbbig-1009981.webp",
   movie:"Spider-Man",
   konc:"hollywood",
   link:""},
   {imgsrc:"https://images5.alphacoders.com/692/thumbbig-692438.webp",
   movie:"Captain America",
   konc:"hollywood",
   link:""},
   {imgsrc:"https://images7.alphacoders.com/868/thumbbig-868807.webp",
   movie:"It",
   konc:"hollywood",
   link:""},
   {imgsrc:"https://images6.alphacoders.com/767/thumbbig-767048.webp",
   movie:"Romantic",
   konc:"hollywood",
   link:""},
   {imgsrc:"https://images6.alphacoders.com/589/thumbbig-589264.webp",
   movie:"FAst and Furios",
   konc:"hollywood",
   link:""},
   {imgsrc:"https://images6.alphacoders.com/682/thumbbig-682809.webp",
   movie:"Batman vs Spiderman",
   konc:"hollywood",
   link:""},
   {imgsrc:"https://images.alphacoders.com/542/thumbbig-542363.webp",
   movie:"Dawn of Justice",
   konc:"hollywood"},
   {imgsrc:"https://images2.alphacoders.com/871/thumbbig-871226.webp",
   movie:"It",
   konc:"hollywood"},
   {imgsrc:"https://images7.alphacoders.com/987/thumbbig-987088.webp",
   movie:"Alita",
   konc:"hollywood"},
   {imgsrc:"https://images2.alphacoders.com/863/thumbbig-863001.webp",
   movie:"black panther",
   konc:"hollywood"},
   {imgsrc:"https://images6.alphacoders.com/901/thumbbig-901701.webp",
   movie:"Black Panther",
   konc:"hollywood"},
   {imgsrc:"https://images6.alphacoders.com/814/thumbbig-814075.webp",
   movie:"Fast and Furious",
   konc:"hollywood"},
   {imgsrc:"https://images2.alphacoders.com/141/thumbbig-141340.webp",
   movie:"Tron",
   konc:"hollywood"},
   {imgsrc:"https://c4.wallpaperflare.com/wallpaper/522/572/1020/movies-bollywood-movies-wallpaper-preview.jpg",
   movie:"Bang Bang",
   konc:"bollywood",
   link:"./Videos/vid-bang.mp4"},
   {imgsrc:"https://wallpapercave.com/wp/wp4252976.jpg",
   movie:"IshqZada",
   konc:"bollywood",
   link:"./Videos/vid-force.mp4"},
   {imgsrc:"https://wallpapercave.com/wp/wp4252978.jpg",
   movie:"CockTail",
   konc:"bollywood",
   link:""},
   {imgsrc:"https://wallpapercave.com/wp/wp4252979.jpg",
   movie:"RajKumar",
   konc:"bollywood",
   link:""},
   {imgsrc:"https://wallpapercave.com/wp/wp4252982.jpg",
   movie:"Jai Ho",
   konc:"bollywood",
   link:""},
   {imgsrc:"https://wallpapercave.com/wp/wp4252984.jpg",
   movie:"Holiday",
   konc:"bollywood",
   link:""},
   {imgsrc:"https://wallpapercave.com/wp/wp4252985.jpg",
   movie:"Ashqui2 ",
   konc:"bollywood",
   link:""},
   {imgsrc:"https://wallpapercave.com/wp/wp3827189.jpg",
   movie:"Rabta",
   konc:"bollywood",
   link:""},
   {imgsrc:"https://wallpapercave.com/wp/wp4252989.jpg",
   movie:"2 state",
   konc:"bollywood",
   link:""},
   {imgsrc:"https://wallpapercave.com/wp/wp2281974.jpg",
   movie:"Rockstar",
   konc:"bollywood",
   link:""},
   {imgsrc:"https://wallpapercave.com/wp/wp4252992.jpg",
   movie:"Hero",
   konc:"bollywood",
   link:""},
   {imgsrc:"https://wallpapercave.com/wp/wp4252994.jpg",
   movie:"Ramaiya Vastiya",
   konc:"bollywood",
   link:""},
   {imgsrc:"https://wallpapercave.com/wp/wp4252995.jpg",
   movie:"Jab Tak ha Jaan",
   konc:"bollywood",
   link:""},
   {imgsrc:"https://wallpapercave.com/wp/wp4252997.jpg",
   movie:"Gunday",
   konc:"bollywood",
   link:""},
   {imgsrc:"https://wallpapercave.com/wp/wp4252999.jpg",
   movie:"Heropanti",
   konc:"bollywood",
   link:""},
   {imgsrc:"https://wallpapercave.com/wp/wp4253000.jpg",
   movie:"7 khoon maaf",
   konc:"bollywood"},
   {imgsrc:"https://wallpapercave.com/wp/wp4253001.jpg",
   movie:"Badrinath ki dulhania",
   konc:"bollywood"},
   {imgsrc:"https://wallpapercave.com/wp/wp4253003.jpg",
   movie:"Veer",
   konc:"bollywood"},
   {imgsrc:"https://wallpapercave.com/wp/wp4253004.jpg",
   movie:"Rush",
   konc:"bollywood"},
   {imgsrc:"https://wallpapercave.com/wp/wp4253007.jpg",
   movie:"Yeh Jawani ha deewani",
   konc:"bollywood"},
   {imgsrc:"https://wallpapercave.com/wp/wp4253010.jpg",
   movie:"Happy New Year",
   konc:"bollywood"},
   {imgsrc:"https://wallpapercave.com/wp/wp4253011.jpg",
   movie:"Baghi 2",
   konc:"bollywood"},
   {imgsrc:"https://wallpapercave.com/wp/wp4253012.jpg",
   movie:"BodyGuard",
   konc:"bollywood"},
   {imgsrc:"https://wallpapercave.com/wp/wp4253014.jpg",
   movie:"Chennai Express",
   konc:"bollywood"},
   {imgsrc:"https://wallpapercave.com/wp/wp4253002.jpg",
   movie:"Krish",
   konc:"bollywood"},
   {imgsrc:"https://wallpapercave.com/wp/wp4252973.jpg",
   movie:"Shaandar",
   konc:"bollywood"},
   {imgsrc:"https://c4.wallpaperflare.com/wallpaper/97/881/138/movies-bollywood-movies-wallpaper-preview.jpg",
   movie:"Krish 3",
   konc:"bollywood"},
   {imgsrc:"https://c4.wallpaperflare.com/wallpaper/650/273/286/movies-bollywood-movies-wallpaper-preview.jpg",
   movie:"Commando",
   konc:"bollywood"},
   {imgsrc:"https://c4.wallpaperflare.com/wallpaper/823/9/90/katrina-kaif-bollywood-movie-posters-shahrukh-khan-jab-tak-hai-jaan-entertainment-bollywood-hd-art-wallpaper-preview.jpg",
   movie:"Jab tak ha jaan ",
   konc:"bollywood"},
   {imgsrc:"https://c4.wallpaperflare.com/wallpaper/1/255/613/movies-bollywood-movies-wallpaper-preview.jpg",
   movie:"sanam teri kasam"},
   {imgsrc:"https://c4.wallpaperflare.com/wallpaper/727/301/175/shraddha-kapoor-in-ungli-wallpaper-preview.jpg",
   movie:"ungli"},
   {imgsrc:"https://c4.wallpaperflare.com/wallpaper/819/258/472/movies-bollywood-movies-wallpaper-preview.jpg",
   movie:"Dilwala"},
   {imgsrc:"https://images.wallpapersden.com/image/ws-amazon-shershaah-movie-2021_78923.jpg",
   movie:" "},
   {imgsrc:"https://images.wallpapersden.com/image/ws-hotstar-dil-bechara_71733.jpg",
   movie:" "},
   {imgsrc:"https://images.wallpapersden.com/image/ws-dabangg_66868.jpg",
   movie:" "},
   {imgsrc:"https://images.wallpapersden.com/image/ws-jagga-jasoos-ranbir-kapoor-katrina-kaif_57935.jpg",
   movie:" "},
   {imgsrc:"https://images.wallpapersden.com/image/ws-bombay-velvet-songs-pics-download_39174.jpg",
   movie:" "},
   {imgsrc:"https://images.wallpapersden.com/image/ws-roy-2015-movie-largest-wallpaper-collection_39456.jpg ",
   movie:" "},
   {imgsrc:""},
];